export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_LOGOUT_START = 'AUTH_LOGOUT_START';
export const AUTH_LOGOUT_SUCCESS = 'AUTH_LOGOUT_SUCCESS';
export const AUTH_LOGOUT_FAIL = 'AUTH_LOGOUT_FAIL';
export const AUTH_FAIL = 'AUTH_FAIL';

export const FB_AUTH_START = 'FB_AUTH_START';
export const FB_AUTH_SUCCESS = 'FB_AUTH_SUCCESS';
export const FB_AUTH_FAIL = 'FB_AUTH_FAIL';

export const USER_REGISTER_START = 'USER_REGISTER_START';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

export const GET_DEPS_START = 'GET_DEPS_START';
export const GET_DEPS_SUCCESS = 'GET_DEPS_SUCCESS';
export const GET_DEPS_ERROR = 'GET_DEPS_ERROR';

export const GET_DEP_START = 'GET_DEP_START';
export const GET_DEP_SUCCESS = 'GET_DEP_SUCCESS';
export const GET_DEP_ERROR = 'GET_DEP_ERROR';

export const PUT_DEP_START = 'PUT_DEP_START';
export const PUT_DEP_SUCCESS = 'PUT_DEP_SUCCESS';
export const PUT_DEP_ERROR = 'PUT_DEP_ERROR';

export const POST_DEP_START = 'POST_DEP_START';
export const POST_DEP_SUCCESS = 'POST_DEP_SUCCESS';
export const POST_DEP_ERROR = 'POST_DEP_ERROR';


export const GET_USRS_START = 'GET_USRS_START';
export const GET_USRS_SUCCESS = 'GET_USRS_SUCCESS';
export const GET_USRS_ERROR = 'GET_USRS_ERROR';

export const GET_USR_START = 'GET_USR_START';
export const GET_USR_SUCCESS = 'GET_USR_SUCCESS';
export const GET_USR_ERROR = 'GET_USR_ERROR';

export const CLR_USR_START = 'CLR_USR_START';
export const CLR_USR_SUCCESS = 'CLR_USR_SUCCESS';
export const CLR_USR_ERROR = 'CLR_USR_ERROR';
export const CLR_USR = 'CLR_USR';

export const PUT_USR_START = 'PUT_USR_START';
export const PUT_USR_SUCCESS = 'PUT_USR_SUCCESS';
export const PUT_USR_ERROR = 'PUT_USR_ERROR';

export const POST_USR_START = 'POST_USR_START';
export const POST_USR_SUCCESS = 'POST_USR_SUCCESS';
export const POST_USR_ERROR = 'POST_USR_ERROR';

export const GET_MOVIE_START = 'GET_MOVIE_START';
export const GET_MOVIE_SUCCESS = 'GET_MOVIE_SUCCESS';
export const GET_MOVIE_ERROR = 'GET_MOVIE_ERROR';

export const GET_MOVIES_START = 'GET_MOVIES_START';
export const GET_MOVIES_SUCCESS = 'GET_MOVIES_SUCCESS';
export const GET_MOVIES_ERROR = 'GET_MOVIES_ERROR';

export const POST_MOVIE_START = 'POST_MOVIE_START';
export const POST_MOVIE_SUCCESS = 'POST_MOVIE_SUCCESS';
export const POST_MOVIE_ERROR = 'POST_MOVIE_ERROR';

export const PUT_MOVIE_START = 'PUT_MOVIE_START';
export const PUT_MOVIE_SUCCESS = 'PUT_MOVIE_SUCCESS';
export const PUT_MOVIE_ERROR = 'PUT_MOVIE_ERROR';

export const GET_CIMAGES_START = 'GET_CIMAGES_START';
export const GET_CIMAGES_SUCCESS = 'GET_CIMAGES_SUCCESS';
export const GET_CIMAGES_ERROR = 'GET_CIMAGES_ERROR';

export const POST_CIMAGES_START = 'POST_CIMAGES_START';
export const POST_CIMAGES_SUCCESS = 'POST_CIMAGES_SUCCESS';
export const POST_CIMAGES_ERROR = 'POST_CIMAGES_ERROR';

export const USR_PROFILE_UPD = 'USR_PROFILE_UPD';

export const POST_CONTACT_START = 'POST_CONTACT_START';
export const POST_CONTACT_SUCCESS = 'POST_CONTACT_SUCCESS';
export const POST_CONTACT_ERROR = 'POST_CONTACT_ERROR';